services:
  database:
    image: postgres:alpine
    restart: always
    env_file:
      - database.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./db_volumes/pg_data:/var/lib/postgresql/data
      # - ./db_volumes/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports: 
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - database
