GET http://localhost:7000
###
GET http://localhost:7000/user
###
POST http://localhost:7000/user/signin
content-type: application/json

{
    "email":"admin@gmail.com",
    "pass":"pass123"
}
###
POST http://localhost:7000/user/signin
content-type: application/json

{
    "email":"adminxx",
    "pass":"pass123"
}
###
GET http://localhost:7000/user/check
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZEhhc2giOiIkMmIkMTAkaUFJWXVmb0JrLm1xUUNNdkNaUi5BdW16UENCVXhNTnBhUWxnQXZEM2RNaWtGVVdtRjdvUWkiLCJpYXQiOjE2NzczNTg3MTYsImV4cCI6MTY3NzM2MjMxNn0.MPRlCZeeyC7skHVgxCiajW2hMohFYpCxAxGaU4km-_8

###
POST http://localhost:7000/user/register
content-type: application/json

{
    "email":"newUser@gmail.com",
    "pass":"Superpassword1",
    "name":"JorMam"
}

###
POST http://localhost:7000/user/signin
content-type: application/json

{
    "email":"newUser@gmail.com",
    "pass":"Superpassword1"
}

###
GET http://localhost:7000/products
###
GET http://localhost:7000/products/1
###
POST http://localhost:7000/products
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJOYW1lIjoiSm9yTWFtIiwiZW1haWwiOiJuZXdVc2VyQGdtYWlsLmNvbSIsImlhdCI6MTY3NzM2NjM1MCwiZXhwIjoxNjc3MzY5OTUwfQ.gl5GEKDisDUA9BXnMD35ZXUnqDO6lUIPlKNOJqOSztc

{
    "sku":"testowy prod",
    "ean":"nowyEan",
    "name":"kij od szczotki"
}
###
PUT http://localhost:7000/products/1
content-type: application/json
x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsInVzZXJOYW1lIjoiSm9yTWFtIiwiZW1haWwiOiJuZXdVc2VyQGdtYWlsLmNvbSIsImlhdCI6MTY3NzM2NjM1MCwiZXhwIjoxNjc3MzY5OTUwfQ.gl5GEKDisDUA9BXnMD35ZXUnqDO6lUIPlKNOJqOSztc

{
    "sku":"testowy prod",
    "ean":"nowyEan",
    "name":"zartowalem"
}